#!/bin/sh
# These lines should be added or sourced to the '.bashrc' or '.zshrc' file

alias ls='ls --color=auto'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                     # human readable sizes
alias free='free -m'                 # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# The 'pacmd list-cards' command shows the possible outputs
# these commands will change the audio output
alias tv-audio='pacmd set-card-profile 1 off && pacmd set-card-profile 0 output:hdmi-stereo-extra2'
alias hs-audio='pacmd set-card-profile 0 off && pacmd set-card-profile 1 output:analog-stereo+input:analog-stereo'

