#!/bin/sh

# Setting up my monitors configurations
# these settings can exported from the program 'arandr'

xrandr --output DVI-D-0 --mode 1920x1080 --pos 3840x0 --rotate left
xrandr --output HDMI-0 --mode 1920x1080 --pos 0x279 --rotate normal
xrandr --output DP-0 --primary --mode 1920x1080 --pos 1920x279 --rate 144.00 --rotate normal --output DP-1 --off


