#!/bin/sh

# Setting up my monitors configurations
# these settings can exported from the program 'arandr'

xrandr --output DVI-D-0 --off
xrandr --output HDMI-0 --mode 1920x1080 --pos 0x201 --rotate normal
xrandr --output DP-0 --primary --mode 2560x1440 --pos 1920x0 --rate 144.00 --rotate normal --output DP-1 --off


