#!/usr/bin/env bash

# This script should show the folders available in ~/work/ and ~/personal/
# if a folder is chosen, tmux will start a session with its name

# It can also be ran with a location/folder as argument
# tmux will initiate a session in this location

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "$HOME/work" "$HOME/personal" -maxdepth 3 -mindepth 1 -type d | fzf)
fi

dirname=`basename $selected`

tmux switch-client -t $dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux send -t $dirname 'source ~/scripts/check_venv' ENTER && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname

